### ISSUE TITLE
Reviewer From Udacity

### ISSUE THREAD

**Issue by kunal121** [hfattahh/Evaluate-news-article-with-NLP-udacity#3]
Hey Hassan,
I did your project review and it was great everything was working perfectly fine but by mistake I sent you the wrong message. The actual message that I want to send you is this
```
Congratulations 🚀🚀💥💥
Great Work Your project meets all the specifications.
please check out project review section for suggestions.
STAY UDACIOUS 😊
```
So please ignore the message I sent you in the review and your project meets all the specifications and doesn't need to submit it again.
I am really very sorry for my mistake.Hope you will understand

**Comment by hfattahh** [comment]
hello man,
never mind. it's a good news
thanks

**Comment by kunal121** [comment]
Thank you so much Hassan for understanding really appreciated 🤗
